# Generated by Django 3.2.12 on 2023-10-29 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0001_initial'),
    ]

    operations = [
    ]
