# Generated by Django 4.2.6 on 2023-12-14 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0003_orgpersonnel_orgscale_and_more'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='orgtypeofpersonnel',
            table_comment=None,
        ),
    ]
