# Generated by Django 3.2.12 on 2023-10-17 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrgDepartment',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('id_category', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'org_department',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrgDeptCategory',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'org_Dept_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrgPersonnelGroup',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('code', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'org_personnel_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrgPosCategory',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'org_pos_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrgPosition',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('is_singularized', models.BooleanField()),
                ('is_idle', models.BooleanField()),
                ('code', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'org_position',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrgProvisionProcedure',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'org_provision_procedure',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrgQualifications',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'org_qualifications',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrgRemunerationItem',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'org_remuneration_item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrgSalaryStructure',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('position_id', models.IntegerField(unique=True)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'org_salary_structure',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrgTypeofPersonnel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'org_typeof_personnel',
                'managed': False,
            },
        ),
    ]
