# Generated by Django 3.2.12 on 2023-10-17 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='orgdeptcategory',
            table='org_dept_category',
        ),
    ]
