# Generated by Django 4.2.7 on 2023-12-11 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0002_alter_orgdeptcategory_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgPersonnel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'org-personnel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrgScale',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=5)),
                ('description', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'org_scale',
                'managed': False,
            },
        ),
        migrations.AlterModelTableComment(
            name='orgposition',
            table_comment='Positions that make up the department',
        ),
        migrations.AlterModelTableComment(
            name='orgtypeofpersonnel',
            table_comment='Funcionario, Laboral, Eventual, Directivo, Funcionario con habilitación especial',
        ),
    ]
