# Generated by Django 4.2.6 on 2023-12-13 19:23

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blogpage_intro_blogpage_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='author',
        ),
        migrations.AddField(
            model_name='blogpage',
            name='intro',
            field=models.CharField(default='intro', max_length=250),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
